#pragma once

#include <map>

#include <gateway/include/ExchangeErrors.h>

namespace singular::gateway::gateio
{

    // Mapping Deribit error codes to GoQuants basic errors
    const std::map<std::string, Errors> GATEIO_ERR_MAP = {

            // Public error codes from 50000-53999
            // General Class
        
             // Request parameter or format related
            {"INVALID_PARAM_VALUE", BadRequest},
            {"INVALID_PROTOCOL", BadRequest},
            {"INVALID_ARGUMENT", BadRequest},
            {"INVALID_REQUEST_BODY", BadRequest},
            {"MISSING_REQUIRED_PARAM", ArgumentsRequired},
            {"BAD_REQUEST", BadRequest},
            {"INVALID_CONTENT_TYPE", BadRequest},
            {"NOT_ACCEPTABLE", BadRequest},
            {"METHOD_NOT_ALLOWED", NotSupported},
            {"NOT_FOUND", BadRequest},

            {"INVALID_CREDENTIALS", AuthenticationError},
            {"INVALID_KEY", AuthenticationError},
            {"IP_FORBIDDEN", PermissionDenied},
            {"READ_ONLY", PermissionDenied},
            {"INVALID_SIGNATURE", AuthenticationError},
            {"MISSING_REQUIRED_HEADER", ArgumentsRequired},
            {"REQUEST_EXPIRED", RequestTimeout},
            {"ACCOUNT_LOCKED", AccountDisabled},
            {"FORBIDDEN", PermissionDenied},

            {"SUB_ACCOUNT_NOT_FOUND", AccountNotEnabled},
            {"SUB_ACCOUNT_LOCKED", AccountDisabled},
            {"MARGIN_BALANCE_EXCEPTION", OperationFailed},
            {"MARGIN_TRANSFER_FAILED", OperationFailed},
            {"TOO_MUCH_FUTURES_AVAILABLE", OperationRejected},
            {"FUTURES_BALANCE_NOT_ENOUGH", InsufficientFunds},
            {"ACCOUNT_EXCEPTION", OperationFailed},
            {"SUB_ACCOUNT_TRANSFER_FAILED", OperationFailed},
            {"ADDRESS_NOT_USED", InvalidAddress},
            {"TOO_FAST", RateLimitExceeded},
            {"WITHDRAWAL_OVER_LIMIT", OperationRejected},
            {"API_WITHDRAW_DISABLED", OnMaintenance},
            {"INVALID_WITHDRAW_ID", InvalidOrder},
            {"INVALID_WITHDRAW_CANCEL_STATUS", OperationRejected},
            {"DUPLICATE_REQUEST", DuplicateOrderId},
            {"ORDER_EXISTS", DuplicateOrderId},
            {"INVALID_CLIENT_ORDER_ID", InvalidOrder},

            {"INVALID_PRECISION", InvalidOrder},
            {"INVALID_CURRENCY", BadSymbol},
            {"INVALID_CURRENCY_PAIR", BadSymbol},
            {"POC_FILL_IMMEDIATELY", OrderImmediatelyFillable},
            {"ORDER_NOT_FOUND", OrderNotFound},
            {"ORDER_CLOSED", OrderNotFound},
            {"ORDER_CANCELLED", CancelPending},
            {"QUANTITY_NOT_ENOUGH", InsufficientFunds},
            {"BALANCE_NOT_ENOUGH", InsufficientFunds},
            {"MARGIN_NOT_SUPPORTED", NotSupported},
            {"MARGIN_BALANCE_NOT_ENOUGH", InsufficientFunds},
            {"AMOUNT_TOO_LITTLE", OperationRejected},
            {"AMOUNT_TOO_MUCH", OperationRejected},
            {"REPEATED_CREATION", DuplicateOrderId},
            {"LOAN_NOT_FOUND", OrderNotFound},
            {"LOAN_RECORD_NOT_FOUND", OrderNotFound},
            {"NO_MATCHED_LOAN", OrderNotFound},
            {"NOT_MERGEABLE", OperationRejected},
            {"NO_CHANGE", NoChange},
            {"REPAY_TOO_MUCH", OperationRejected},
            {"TOO_MANY_CURRENCY_PAIRS", OperationRejected},
            {"TOO_MANY_ORDERS", RateLimitExceeded},
            {"MIXED_ACCOUNT_TYPE", OperationRejected},
            {"AUTO_BORROW_TOO_MUCH", InsufficientFunds},
            {"TRADE_RESTRICTED", PermissionDenied},
            {"FOK_NOT_FILL", OrderNotFillable},
            {"INITIAL_MARGIN_TOO_LOW", OperationRejected},
            {"NO_MERGEABLE_ORDERS", OperationRejected},
            {"ORDER_BOOK_NOT_FOUND", ContractUnavailable},
            {"FAILED_RETRIEVE_ASSETS", OperationFailed},
            {"CANCEL_FAIL", OperationFailed},

            {"USER_NOT_FOUND", AccountNotEnabled},
            {"CONTRACT_NO_COUNTER", ContractUnavailable},
            {"CONTRACT_NOT_FOUND", ContractUnavailable},
            {"RISK_LIMIT_EXCEEDED", OperationRejected},
            {"INSUFFICIENT_AVAILABLE", InsufficientFunds},
            {"LIQUIDATE_IMMEDIATELY", OperationRejected},
            {"LEVERAGE_TOO_HIGH", OperationRejected},
            {"LEVERAGE_TOO_LOW", OperationRejected},
            {"ORDER_NOT_FOUND", OrderNotFound},
            {"ORDER_NOT_OWNED", OperationRejected},
            {"ORDER_FINISHED", OrderNotFound},
            {"TOO_MANY_ORDERS", RateLimitExceeded},
            {"POSITION_CROSS_MARGIN", OperationRejected},
            {"POSITION_IN_LIQUIDATION", OperationRejected},
            {"POSITION_IN_CLOSE", OperationRejected},
            {"POSITION_EMPTY", OrderNotFound},
            {"REMOVE_TOO_MUCH", OperationRejected},
            {"RISK_LIMIT_NOT_MULTIPLE", OperationRejected},
            {"RISK_LIMIT_TOO_HIGH", OperationRejected},
            {"RISK_LIMIT_TOO_LOW", OperationRejected},
            {"PRICE_TOO_DEVIATED", OperationRejected},
            {"SIZE_TOO_LARGE", OperationRejected},
            {"SIZE_TOO_SMALL", OperationRejected},
            {"PRICE_OVER_LIQUIDATION", OperationRejected},
            {"PRICE_OVER_BANKRUPT", OperationRejected},
            {"ORDER_POC_IMMEDIATE", OrderImmediatelyFillable},
            {"INCREASE_POSITION", OperationRejected},
            {"CONTRACT_IN_DELISTING", ContractUnavailable},
            {"POSITION_NOT_FOUND", OrderNotFound},
            {"POSITION_DUAL_MODE", OperationRejected},
            {"ORDER_PENDING", OperationRejected},
            {"POSITION_HOLDING", OperationRejected},
            {"REDUCE_EXCEEDED", OperationRejected},
            {"AMEND_WITH_STOP", OperationRejected},
            {"ORDER_FOK", OrderNotFillable},

            {"COL_NOT_ENOUGH", InsufficientFunds},
            {"COL_TOO_MUCH", OperationRejected},
            {"INIT_LTV_TOO_HIGH", OperationRejected},
            {"REDEEMED_LTV_TOO_HIGH", OperationRejected},
            {"BORROWABLE_NOT_ENOUGH", InsufficientFunds},
            {"ORDER_TOO_MANY_TOTAL", RateLimitExceeded},
            {"ORDER_TOO_MANY_DAILY", RateLimitExceeded},
            {"ORDER_TOO_MANY_USER", RateLimitExceeded},
            {"ORDER_NOT_EXIST", OrderNotFound},
            {"ORDER_FINISHED", OrderNotFound},
            {"ORDER_NO_PAY", NoChange},
            {"ORDER_EXIST", DuplicateOrderId},
            {"ORDER_HISTORY_EXIST", DuplicateOrderId},
            {"ORDER_REPAYING", OperationRejected},
            {"ORDER_LIQUIDATING", OperationRejected},
            {"BORROW_TOO_LITTLE", OperationRejected},
            {"BORROW_TOO_LARGE", OperationRejected},
            {"REPAY_AMOUNT_INVALID", OperationRejected},
            {"REPAY_GREATER_THAN_AVAILABLE", OperationRejected},
            {"POOL_BALANCE_NOT_ENOUGH", InsufficientFunds},
            {"CURRENCY_SETTLING", OperationRejected},
            {"RISK_REJECT", OperationRejected},
            {"LOAN_FAILED", OperationRejected},

            {"USER_LIAB", OperationRejected},
            {"USER_PENDING_ORDERS", OperationRejected},
            {"MODE_SET", MarginModeAlreadySet},

            {"ERR_BALANCE_NOT_ENOUGH", InsufficientFunds},
            {"ERR_PRODUCT_SELL_OUT", OperationRejected},
            {"ERR_PRODUCT_BUY", OperationRejected},
            {"ERR_CREATE_ORDER", OperationRejected},
            {"ERR_QUOTA_LOWER_LIMIT", OperationRejected},
            {"ERR_QUOTA_SUPERIOR_LIMIT", OperationRejected},
            {"ERR_ORDER_NUMBER_LIMIT", RateLimitExceeded},
            {"ERR_PRODUCT_CLOSE", ContractUnavailable},
            {"COPIES_NOT_ENOUGH", InsufficientFunds},
            {"COPIES_TOO_SMALL", OperationRejected},
            {"COPIES_TOO_BIG", OperationRejected},
            {"TOTAL_AMOUNT_24", RateLimitExceeded},
            {"TOTAL_BUYCOUNT_24", RateLimitExceeded},
            {"REDEEM_24_LIMIT", OperationRejected},

            {"INTERNAL", ExchangeError},
            {"SERVER_ERROR", ExchangeError},
            {"TOO_BUSY", ExchangeNotAvailable}

    };
};